from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

try:
    from .programstart_recommend import ProjectRecommendation
except ImportError:  # pragma: no cover - standalone script execution fallback
    from programstart_recommend import ProjectRecommendation


@dataclass(slots=True)
class StarterScaffoldPlan:
    label: str
    root_dir: str
    run_hint: str
    files: dict[str, str]


def slugify_project_name(project_name: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "_", project_name.strip()).strip("_").lower()
    return slug or "generated_app"


def has_stack(recommendation: ProjectRecommendation, stack_name: str) -> bool:
    stack_names = {item.lower() for item in recommendation.stack_names}
    return stack_name.lower() in stack_names


def has_service(recommendation: ProjectRecommendation, service_name: str) -> bool:
    service_names = {item.lower() for item in recommendation.service_names}
    return service_name.lower() in service_names


def has_api(recommendation: ProjectRecommendation, api_name: str) -> bool:
    api_names = {item.lower() for item in recommendation.api_names}
    return api_name.lower() in api_names


def toml_string_list(items: list[str]) -> str:
    if not items:
        return "[]"
    lines = ["["]
    lines.extend(f'  "{item}",' for item in items)
    lines.append("]")
    return "\n".join(lines)


def starter_readme(project_name: str, recommendation: ProjectRecommendation, plan: StarterScaffoldPlan) -> str:
    stacks = ", ".join(recommendation.stack_names) if recommendation.stack_names else "No stack hints available"
    services = ", ".join(recommendation.service_names) if recommendation.service_names else "No external services inferred"
    return (
        f"# Starter Scaffold - {project_name}\n\n"
        "This scaffold is a runnable starting point generated by `programstart create`.\n\n"
        f"- Product shape: {recommendation.product_shape}\n"
        f"- Variant: {recommendation.variant}\n"
        f"- Archetype: {recommendation.archetype}\n"
        f"- Recommended stacks: {stacks}\n"
        f"- Inferred services: {services}\n"
        f"- Scaffold root: {plan.root_dir}\n"
        f"- Run hint: {plan.run_hint}\n\n"
        "Treat this as an implementation starter, not a source-of-truth planning document.\n"
    )


def service_env_example(project_name: str, recommendation: ProjectRecommendation, root_dir: str) -> tuple[str, str] | None:
    lines = [
        f"# Environment template for {project_name}",
        "# Fill these values in the generated project repo after provisioning.",
        "# Non-secret IDs and URLs may be hydrated automatically after supported provisioning runs.",
        "",
    ]
    shape = recommendation.product_shape
    added = False

    if has_service(recommendation, "Supabase"):
        added = True
        lines.extend(
            [
                "# Supabase",
                "SUPABASE_PROJECT_REF=",
                "SUPABASE_REGION=",
                "SUPABASE_URL=",
                "SUPABASE_ANON_KEY=",
                "SUPABASE_SERVICE_ROLE_KEY=",
            ]
        )
        if shape in {"web app", "mobile app"}:
            lines.extend(
                [
                    "NEXT_PUBLIC_SUPABASE_URL=",
                    "NEXT_PUBLIC_SUPABASE_ANON_KEY=",
                ]
            )
        lines.append("")

    if has_service(recommendation, "Vercel"):
        added = True
        lines.extend(
            [
                "# Vercel deployment metadata",
                "VERCEL_PROJECT_ID=",
                "VERCEL_PROJECT_NAME=",
                "VERCEL_TEAM_ID=",
                "VERCEL_TEAM_SLUG=",
                "VERCEL_DEPLOY_HOOK_URL=",
                "",
            ]
        )

    if has_service(recommendation, "Neon"):
        added = True
        lines.extend(
            [
                "# Neon Postgres",
                "NEON_PROJECT_ID=",
                "NEON_BRANCH_ID=",
                "NEON_REGION=",
                "NEON_HOST=",
                "NEON_DATABASE=",
                "DATABASE_URL=",
                "DIRECT_DATABASE_URL=",
                "",
            ]
        )

    if not added:
        return None

    return (f"{root_dir}/.env.example", "\n".join(lines).rstrip() + "\n")


def api_env_example(project_name: str, recommendation: ProjectRecommendation, root_dir: str) -> tuple[str, str] | None:
    lines = [
        f"# Third-party API template for {project_name}",
        "# Keep server-side secrets out of version control and out of client bundles.",
        "",
    ]
    added = False

    if has_api(recommendation, "OpenAI"):
        added = True
        lines.extend(
            [
                "# OpenAI",
                "OPENAI_API_KEY=",
                "OPENAI_MODEL=",
                "OPENAI_ORGANIZATION_ID=",
                "OPENAI_PROJECT_ID=",
                "",
            ]
        )

    if has_api(recommendation, "Anthropic"):
        added = True
        lines.extend(
            [
                "# Anthropic",
                "ANTHROPIC_API_KEY=",
                "ANTHROPIC_MODEL=",
                "ANTHROPIC_VERSION=2023-06-01",
                "",
            ]
        )

    if has_api(recommendation, "Stripe"):
        added = True
        lines.extend(
            [
                "# Stripe",
                "STRIPE_SECRET_KEY=",
                "STRIPE_WEBHOOK_SECRET=",
                "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=",
                "",
            ]
        )

    if has_api(recommendation, "RevenueCat"):
        added = True
        lines.extend(
            [
                "# RevenueCat",
                "REVENUECAT_API_KEY=",
                "REVENUECAT_PROJECT_ID=",
                "EXPO_PUBLIC_REVENUECAT_API_KEY=",
                "",
            ]
        )

    if has_api(recommendation, "Ably"):
        added = True
        lines.extend(
            [
                "# Ably",
                "ABLY_API_KEY=",
                "NEXT_PUBLIC_ABLY_CLIENT_KEY=",
                "",
            ]
        )

    if has_api(recommendation, "Pusher"):
        added = True
        lines.extend(
            [
                "# Pusher",
                "PUSHER_APP_ID=",
                "PUSHER_KEY=",
                "PUSHER_SECRET=",
                "NEXT_PUBLIC_PUSHER_KEY=",
                "NEXT_PUBLIC_PUSHER_CLUSTER=",
                "",
            ]
        )

    if has_api(recommendation, "Segment"):
        added = True
        lines.extend(
            [
                "# Segment",
                "SEGMENT_WRITE_KEY=",
                "NEXT_PUBLIC_SEGMENT_WRITE_KEY=",
                "",
            ]
        )

    if has_api(recommendation, "Shippo"):
        added = True
        lines.extend(
            [
                "# Shippo",
                "SHIPPO_API_TOKEN=",
                "",
            ]
        )

    if has_api(recommendation, "TaxJar"):
        added = True
        lines.extend(
            [
                "# TaxJar",
                "TAXJAR_API_KEY=",
                "",
            ]
        )

    if has_api(recommendation, "Resend"):
        added = True
        lines.extend(
            [
                "# Resend",
                "RESEND_API_KEY=",
                "RESEND_FROM_EMAIL=",
                "",
            ]
        )

    if has_api(recommendation, "PostHog"):
        added = True
        lines.extend(
            [
                "# PostHog",
                "NEXT_PUBLIC_POSTHOG_KEY=",
                "NEXT_PUBLIC_POSTHOG_HOST=",
                "POSTHOG_PERSONAL_API_KEY=",
                "",
            ]
        )

    if has_api(recommendation, "Sentry"):
        added = True
        lines.extend(
            [
                "# Sentry",
                "SENTRY_AUTH_TOKEN=",
                "SENTRY_ORG=",
                "SENTRY_PROJECT=",
                "NEXT_PUBLIC_SENTRY_DSN=",
                "",
            ]
        )

    if not added:
        return None

    return (f"{root_dir}/.env.example", "\n".join(lines).rstrip() + "\n")


def build_cli_tool_plan(project_name: str, recommendation: ProjectRecommendation) -> StarterScaffoldPlan:
    package_name = slugify_project_name(project_name)
    root_dir = "starter/cli_tool"
    dev_dependencies = ["pytest>=8.0", "ruff>=0.12.10"]
    if has_stack(recommendation, "Hypothesis"):
        dev_dependencies.append("hypothesis>=6.100.0")
    return StarterScaffoldPlan(
        label="CLI tool",
        root_dir=root_dir,
        run_hint=f"uv run --project {root_dir} {package_name} --help",
        files={
            f"{root_dir}/pyproject.toml": (
                "[build-system]\n"
                'requires = ["setuptools>=75"]\n'
                'build-backend = "setuptools.build_meta"\n\n'
                "[project]\n"
                f'name = "{package_name}"\n'
                'version = "0.1.0"\n'
                f'description = "Starter CLI scaffold for {project_name}"\n'
                'requires-python = ">=3.12"\n\n'
                f"dependencies = {toml_string_list(['pydantic>=2.0'])}\n\n"
                "[project.optional-dependencies]\n"
                f"dev = {toml_string_list(dev_dependencies)}\n\n"
                "[project.scripts]\n"
                f'{package_name} = "{package_name}.main:main"\n\n'
                "[tool.setuptools.package-dir]\n"
                '"" = "src"\n\n'
                "[tool.setuptools.packages.find]\n"
                'where = ["src"]\n\n'
                "[tool.pytest.ini_options]\n"
                'pythonpath = ["src"]\n'
            ),
            f"{root_dir}/src/{package_name}/__init__.py": '__all__ = ["main"]\n',
            f"{root_dir}/src/{package_name}/models.py": (
                "from __future__ import annotations\n\n"
                "from pydantic import BaseModel, Field\n\n\n"
                "class GreetingRequest(BaseModel):\n"
                "    name: str = Field(min_length=1, max_length=64)\n"
                "    enthusiasm: int = Field(default=1, ge=1, le=5)\n"
            ),
            f"{root_dir}/src/{package_name}/main.py": (
                "from __future__ import annotations\n\n"
                "import argparse\n\n\n"
                f"from {package_name}.models import GreetingRequest\n\n\n"
                "def build_parser() -> argparse.ArgumentParser:\n"
                f'    parser = argparse.ArgumentParser(description="Starter CLI for {project_name}.")\n'
                '    parser.add_argument("--name", default="world", help="Name to greet.")\n'
                '    parser.add_argument("--enthusiasm", type=int, default=1, help="Greeting intensity from 1 to 5.")\n'
                "    return parser\n\n\n"
                "def main() -> int:\n"
                "    parser = build_parser()\n"
                "    args = parser.parse_args()\n"
                "    payload = GreetingRequest(name=args.name, enthusiasm=args.enthusiasm)\n"
                '    print(f"hello, {payload.name}{"!" * payload.enthusiasm}")\n'
                "    return 0\n\n\n"
                'if __name__ == "__main__":\n'
                "    raise SystemExit(main())\n"
            ),
            f"{root_dir}/tests/test_main.py": (
                "from __future__ import annotations\n\n"
                f"from {package_name}.models import GreetingRequest\n\n\n"
                "def test_greeting_request_defaults() -> None:\n"
                '    payload = GreetingRequest(name="planner")\n'
                '    assert payload.name == "planner"\n'
                "    assert payload.enthusiasm == 1\n"
            ),
            f"{root_dir}/README.md": (
                f"# {project_name} CLI Starter\n\n"
                "This scaffold mirrors the recommended Python CLI stack: uv packaging, "
                "Pydantic input modeling, and pytest-based tests.\n"
            ),
        },
    )


def build_cli_hypothesis_test(project_name: str, recommendation: ProjectRecommendation) -> tuple[str, str] | None:
    if not has_stack(recommendation, "Hypothesis"):
        return None
    package_name = slugify_project_name(project_name)
    return (
        "starter/cli_tool/tests/test_models_property.py",
        (
            "from __future__ import annotations\n\n"
            "from hypothesis import given\n"
            "from hypothesis import strategies as st\n\n"
            f"from {package_name}.models import GreetingRequest\n\n\n"
            "@given(st.text(min_size=1, max_size=32), st.integers(min_value=1, max_value=5))\n"
            "def test_greeting_request_accepts_supported_values(name: str, enthusiasm: int) -> None:\n"
            "    payload = GreetingRequest(name=name, enthusiasm=enthusiasm)\n"
            "    assert payload.name == name\n"
            "    assert payload.enthusiasm == enthusiasm\n"
        ),
    )


def build_api_service_plan(project_name: str, recommendation: ProjectRecommendation) -> StarterScaffoldPlan:
    package_name = slugify_project_name(project_name)
    root_dir = "starter/api_service"
    dependencies = ["fastapi>=0.115.12,<0.116.0", "pydantic>=2.0", "uvicorn[standard]>=0.35.0"]
    optional_dev = ["httpx>=0.28.0", "pytest>=8.0"]
    if has_stack(recommendation, "LiteLLM"):
        dependencies.append("litellm>=1.40.0")
    if has_stack(recommendation, "Instructor"):
        dependencies.append("instructor>=1.3.0")
    if has_stack(recommendation, "ChromaDB"):
        dependencies.append("chromadb>=0.4.0")
    if has_stack(recommendation, "Temporal"):
        dependencies.append("temporalio>=1.8.0")
    return StarterScaffoldPlan(
        label="API service",
        root_dir=root_dir,
        run_hint="uv run --project starter/api_service uvicorn app.main:app --reload",
        files={
            f"{root_dir}/pyproject.toml": (
                "[build-system]\n"
                'requires = ["setuptools>=75"]\n'
                'build-backend = "setuptools.build_meta"\n\n'
                "[project]\n"
                f'name = "{package_name}-api"\n'
                'version = "0.1.0"\n'
                f'description = "FastAPI starter service for {project_name}"\n'
                'requires-python = ">=3.12"\n'
                f"dependencies = {toml_string_list(dependencies)}\n\n"
                "[project.optional-dependencies]\n"
                f"dev = {toml_string_list(optional_dev)}\n\n"
                "[tool.pytest.ini_options]\n"
                'pythonpath = ["."]\n'
            ),
            f"{root_dir}/app/__init__.py": "",
            f"{root_dir}/app/config.py": (
                "from __future__ import annotations\n\n"
                "from dataclasses import asdict, dataclass\n\n\n"
                "@dataclass(slots=True)\n"
                "class ServiceSettings:\n"
                f'    service_name: str = "{slugify_project_name(project_name)}-api"\n'
                '    version: str = "0.1.0"\n'
                '    environment: str = "development"\n\n'
                "    def model_dump(self) -> dict[str, str]:\n"
                "        return asdict(self)\n"
            ),
            f"{root_dir}/app/main.py": (
                "from __future__ import annotations\n\n"
                "from fastapi import FastAPI\n\n"
                "from app.config import ServiceSettings\n\n\n"
                "settings = ServiceSettings()\n"
                "app = FastAPI(title=settings.service_name, version=settings.version)\n\n\n"
                '@app.get("/health")\n'
                "def health() -> dict[str, str]:\n"
                '    return {"status": "ok", "service": settings.service_name}\n\n\n'
                '@app.get("/")\n'
                "def root() -> dict[str, object]:\n"
                "    return {\n"
                '        "service": settings.service_name,\n'
                '        "environment": settings.environment,\n'
                '        "recommended_stacks": ["FastAPI", "Pydantic"],\n'
                "    }\n"
            ),
            f"{root_dir}/tests/test_health.py": (
                "from __future__ import annotations\n\n"
                "from fastapi.testclient import TestClient\n\n"
                "from app.main import app\n\n\n"
                "def test_health_endpoint() -> None:\n"
                "    client = TestClient(app)\n"
                '    response = client.get("/health")\n'
                "    assert response.status_code == 200\n"
                '    assert response.json()["status"] == "ok"\n'
            ),
            f"{root_dir}/README.md": (
                f"# {project_name} API Starter\n\n"
                "This scaffold mirrors the recommended FastAPI-first service stack and leaves "
                "room for retrieval, observability, and durable workflow modules when those "
                "stacks are selected.\n"
            ),
        },
    )


def build_api_optional_files(project_name: str, recommendation: ProjectRecommendation) -> dict[str, str]:
    root_dir = "starter/api_service"
    files: dict[str, str] = {}
    if has_stack(recommendation, "LiteLLM") or has_stack(recommendation, "Instructor"):
        files[f"{root_dir}/app/ai.py"] = (
            "from __future__ import annotations\n\n"
            "def build_llm_router_hint() -> dict[str, str]:\n"
            "    return {\n"
            '        "provider": "litellm",\n'
            '        "validation": "instructor",\n'
            '        "next_step": "centralize provider routing before shipping model features",\n'
            "    }\n"
        )
    if has_stack(recommendation, "ChromaDB"):
        files[f"{root_dir}/app/retrieval.py"] = (
            "from __future__ import annotations\n\n"
            "def retrieval_backend() -> dict[str, str]:\n"
            "    return {\n"
            '        "vector_store": "chromadb",\n'
            '        "sync_rule": "preserve authoritative planning sources in retrieval corpus",\n'
            "    }\n"
        )
    if has_stack(recommendation, "Temporal") or has_stack(recommendation, "LangGraph"):
        files[f"{root_dir}/app/workflows.py"] = (
            "from __future__ import annotations\n\n"
            "def orchestration_plan() -> dict[str, str]:\n"
            "    return {\n"
            '        "durable_engine": "temporal",\n'
            '        "agent_graph": "langgraph",\n'
            '        "policy": "use durable workflows for long-running automation",\n'
            "    }\n"
        )
    if has_stack(recommendation, "OpenTelemetry"):
        files[f"{root_dir}/app/observability.py"] = (
            "from __future__ import annotations\n\n"
            "def telemetry_resource_attributes() -> dict[str, str]:\n"
            "    return {\n"
            '        "instrumentation": "opentelemetry",\n'
            '        "service.namespace": "starter",\n'
            "    }\n"
        )
    return files


def build_web_app_plan(project_name: str, recommendation: ProjectRecommendation) -> StarterScaffoldPlan:
    root_dir = "starter/web_app"
    dev_dependency_lines = [
        '    "typescript": "^6",\n',
        '    "@types/node": "^25",\n',
        '    "@types/react": "^19",\n',
        '    "@types/react-dom": "^19"\n',
    ]
    if has_stack(recommendation, "Playwright"):
        dev_dependency_lines.insert(0, '    "@playwright/test": "^1",\n')
    package_json = (
        "{\n"
        f'  "name": "{slugify_project_name(project_name)}-web",\n'
        '  "private": true,\n'
        '  "scripts": {\n'
        '    "dev": "next dev",\n'
        '    "build": "next build",\n'
        '    "start": "next start",\n'
        '    "lint": "next lint"\n'
        "  },\n"
        '  "dependencies": {\n'
        '    "next": "^16",\n'
        '    "react": "^19",\n'
        '    "react-dom": "^19"\n'
        "  },\n"
        '  "devDependencies": {\n' + "".join(dev_dependency_lines) + "  }\n" + "}\n"
    )
    files = {
        f"{root_dir}/package.json": package_json,
        f"{root_dir}/tsconfig.json": (
            "{\n"
            '  "compilerOptions": {\n'
            '    "target": "ES2022",\n'
            '    "lib": ["dom", "dom.iterable", "es2022"],\n'
            '    "allowJs": false,\n'
            '    "skipLibCheck": true,\n'
            '    "strict": true,\n'
            '    "noEmit": true,\n'
            '    "module": "esnext",\n'
            '    "moduleResolution": "bundler",\n'
            '    "resolveJsonModule": true,\n'
            '    "isolatedModules": true,\n'
            '    "jsx": "preserve",\n'
            '    "incremental": true\n'
            "  },\n"
            '  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],\n'
            '  "exclude": ["node_modules"]\n'
            "}\n"
        ),
        f"{root_dir}/next.config.mjs": "const nextConfig = {};\n\nexport default nextConfig;\n",
        f"{root_dir}/next-env.d.ts": '/// <reference types="next" />\n/// <reference types="next/image-types/global" />\n\n',
        f"{root_dir}/app/layout.tsx": (
            'import type { ReactNode } from "react";\n'
            'import "./globals.css";\n\n'
            "type RootLayoutProps = {\n"
            "  children: ReactNode;\n"
            "};\n\n"
            f'export const metadata = {{ title: "{project_name}", description: "Generated by PROGRAMSTART" }};\n\n'
            "export default function RootLayout({ children }: RootLayoutProps) {\n"
            "  return (\n"
            '    <html lang="en">\n'
            "      <body>{children}</body>\n"
            "    </html>\n"
            "  );\n"
            "}\n"
        ),
        f"{root_dir}/app/page.tsx": (
            "const signals = [\n"
            '  "Workflow-first planning",\n'
            '  "State and routing discipline",\n'
            '  "Activation clarity before implementation",\n'
            "];\n\n"
            "export default function HomePage() {\n"
            "  return (\n"
            '    <main className="shell">\n'
            '      <section className="hero">\n'
            f'        <p className="eyebrow">{project_name}</p>\n'
            "        <h1>Next.js starter aligned to the recommended product stack.</h1>\n"
            '        <p className="lede">Use this shell to connect real routes, auth, and '
            "activation logic after the planning package is approved.</p>\n"
            "      </section>\n"
            '      <section className="signals">\n'
            "        {signals.map((signal) => (\n"
            '          <article key={signal} className="card">\n'
            "            <strong>{signal}</strong>\n"
            "          </article>\n"
            "        ))}\n"
            "      </section>\n"
            "    </main>\n"
            "  );\n"
            "}\n"
        ),
        f"{root_dir}/app/globals.css": (
            ":root {\n"
            "  color-scheme: light;\n"
            "  --bg: #f6f0e5;\n"
            "  --panel: #fff9f0;\n"
            "  --ink: #1f221c;\n"
            "  --accent: #0b6e4f;\n"
            "  --border: rgba(31, 34, 28, 0.12);\n"
            "}\n\n"
            "* { box-sizing: border-box; }\n\n"
            "body {\n"
            "  margin: 0;\n"
            "  min-height: 100vh;\n"
            "  font-family: Georgia, serif;\n"
            "  color: var(--ink);\n"
            "  background: radial-gradient(circle at top, #fff7e0 0%, var(--bg) 55%, #d9eadf 100%);\n"
            "}\n\n"
            ".shell {\n"
            "  width: min(72rem, calc(100% - 2rem));\n"
            "  margin: 0 auto;\n"
            "  padding: 5rem 0 4rem;\n"
            "}\n\n"
            ".hero {\n"
            "  padding: 2rem;\n"
            "  border: 1px solid var(--border);\n"
            "  background: rgba(255, 249, 240, 0.88);\n"
            "}\n\n"
            ".eyebrow {\n"
            "  text-transform: uppercase;\n"
            "  letter-spacing: 0.14em;\n"
            "  color: var(--accent);\n"
            "}\n\n"
            ".lede {\n"
            "  max-width: 48rem;\n"
            "}\n\n"
            ".signals {\n"
            "  display: grid;\n"
            "  grid-template-columns: repeat(auto-fit, minmax(14rem, 1fr));\n"
            "  gap: 1rem;\n"
            "  margin-top: 1.5rem;\n"
            "}\n\n"
            ".card {\n"
            "  padding: 1rem;\n"
            "  border: 1px solid var(--border);\n"
            "  background: rgba(255, 255, 255, 0.7);\n"
            "}\n"
        ),
        f"{root_dir}/README.md": (
            f"# {project_name} Web Starter\n\n"
            "This scaffold mirrors the recommended Next.js app-router stack and gives you a "
            "real package manifest, route shell, and styling baseline instead of a static "
            "HTML placeholder.\n"
        ),
    }
    if has_stack(recommendation, "Playwright"):
        files[f"{root_dir}/playwright.config.ts"] = (
            'import { defineConfig } from "@playwright/test";\n\n'
            "export default defineConfig({\n"
            '  testDir: "./e2e",\n'
            '  use: { baseURL: "http://127.0.0.1:3000" },\n'
            "});\n"
        )
        files[f"{root_dir}/e2e/home.spec.ts"] = (
            'import { test, expect } from "@playwright/test";\n\n'
            'test("home page renders stack guidance", async ({ page }) => {\n'
            '  await page.goto("/");\n'
            '  await expect(page.getByText("recommended product stack")).toBeVisible();\n'
            "});\n"
        )
    return StarterScaffoldPlan(
        label="Web app",
        root_dir=root_dir,
        run_hint="npm install && npm run dev",
        files=files,
    )


def build_mobile_app_plan(project_name: str, recommendation: ProjectRecommendation) -> StarterScaffoldPlan:
    root_dir = "starter/mobile_app"
    dependency_lines = [
        '    "expo": "~53.0.20",\n',
        '    "expo-status-bar": "~2.2.3",\n',
        '    "react": "^19",\n',
        '    "react-native": "^0.85"\n',
    ]
    if has_stack(recommendation, "Firebase"):
        dependency_lines.insert(-1, '    "firebase": "^12",\n')
    package_json = (
        "{\n"
        f'  "name": "{slugify_project_name(project_name)}-mobile",\n'
        '  "private": true,\n'
        '  "scripts": {\n'
        '    "start": "expo start",\n'
        '    "android": "expo start --android",\n'
        '    "ios": "expo start --ios",\n'
        '    "web": "expo start --web"\n'
        "  },\n"
        '  "dependencies": {\n' + "".join(dependency_lines) + "  },\n"
        '  "devDependencies": {\n'
        '    "typescript": "^6",\n'
        '    "@types/react": "^19"\n'
        "  }\n" + "}\n"
    )
    return StarterScaffoldPlan(
        label="Mobile app",
        root_dir=root_dir,
        run_hint="npm install && npm run start",
        files={
            f"{root_dir}/package.json": package_json,
            f"{root_dir}/app.json": (
                "{\n"
                f'  "expo": {{\n    "name": "{project_name}",\n'
                f'    "slug": "{slugify_project_name(project_name)}-mobile",\n'
                '    "scheme": "starterapp",\n'
                '    "platforms": ["ios", "android", "web"]\n'
                "  }\n"
                "}\n"
            ),
            f"{root_dir}/App.tsx": (
                'import { StatusBar } from "expo-status-bar";\n'
                'import { SafeAreaView, StyleSheet, Text, View } from "react-native";\n\n'
                "const priorities = [\n"
                '  "Activation-ready onboarding",\n'
                '  "Subscription and entitlement discipline",\n'
                '  "Environment wiring before store submission",\n'
                "];\n\n"
                "export default function App() {\n"
                "  return (\n"
                "    <SafeAreaView style={styles.shell}>\n"
                '      <StatusBar style="dark" />\n'
                "      <View style={styles.hero}>\n"
                f"        <Text style={{styles.eyebrow}}>{project_name}</Text>\n"
                "        <Text style={styles.title}>Expo starter aligned to the recommended mobile stack.</Text>\n"
                "        <Text style={styles.lede}>Use this shell to connect auth, purchases, and push flows after the planning package is approved.</Text>\n"
                "      </View>\n"
                "      <View style={styles.list}>\n"
                "        {priorities.map((item) => (\n"
                "          <View key={item} style={styles.card}>\n"
                "            <Text style={styles.cardText}>{item}</Text>\n"
                "          </View>\n"
                "        ))}\n"
                "      </View>\n"
                "    </SafeAreaView>\n"
                "  );\n"
                "}\n\n"
                "const styles = StyleSheet.create({\n"
                "  shell: { flex: 1, backgroundColor: '#f6f3ea', paddingHorizontal: 20, paddingTop: 24 },\n"
                "  hero: { gap: 12, marginBottom: 24 },\n"
                "  eyebrow: { textTransform: 'uppercase', letterSpacing: 2, color: '#0f766e' },\n"
                "  title: { fontSize: 32, lineHeight: 38, color: '#1f2937', fontWeight: '700' },\n"
                "  lede: { fontSize: 16, lineHeight: 24, color: '#475569' },\n"
                "  list: { gap: 12 },\n"
                "  card: { borderWidth: 1, borderColor: '#d6d3d1', backgroundColor: '#fffdf8', padding: 16, borderRadius: 18 },\n"
                "  cardText: { fontSize: 15, color: '#1f2937' },\n"
                "});\n"
            ),
            f"{root_dir}/tsconfig.json": '{\n  "extends": "expo/tsconfig.base",\n  "compilerOptions": {\n    "strict": true\n  }\n}\n',
            f"{root_dir}/README.md": (
                f"# {project_name} Mobile Starter\n\n"
                "This scaffold mirrors the recommended Expo and React Native path so mobile-specific auth, purchases, and release wiring start from a native-first baseline.\n"
            ),
        },
    )


def build_web_optional_files(recommendation: ProjectRecommendation) -> dict[str, str]:
    root_dir = "starter/web_app"
    files: dict[str, str] = {}
    if has_stack(recommendation, "Yjs") or has_api(recommendation, "Ably") or has_api(recommendation, "Pusher"):
        files[f"{root_dir}/lib/realtime.ts"] = (
            "export function realtimePlan() {\n"
            "  return {\n"
            f'    transport: "{"ably" if has_api(recommendation, "Ably") else "pusher" if has_api(recommendation, "Pusher") else "custom"}",\n'
            f'    collaborationModel: "{"yjs" if has_stack(recommendation, "Yjs") else "event-stream"}",\n'
            '    nextStep: "define presence, permissions, and conflict resolution before wiring live state",\n'
            "  };\n"
            "}\n"
        )
    if has_api(recommendation, "Segment") or has_api(recommendation, "Shippo") or has_api(recommendation, "TaxJar"):
        files[f"{root_dir}/lib/commerce.ts"] = (
            "export function commerceIntegrationChecklist() {\n"
            "  return [\n"
            f'    "analytics-routing: {"segment" if has_api(recommendation, "Segment") else "not-selected"}",\n'
            f'    "shipping: {"shippo" if has_api(recommendation, "Shippo") else "not-selected"}",\n'
            f'    "tax: {"taxjar" if has_api(recommendation, "TaxJar") else "not-selected"}",\n'
            '    "validate identifiers and webhook ownership before production enablement",\n'
            "  ];\n"
            "}\n"
        )
    return files


def build_mobile_optional_files(recommendation: ProjectRecommendation) -> dict[str, str]:
    root_dir = "starter/mobile_app"
    files: dict[str, str] = {}
    if has_api(recommendation, "RevenueCat"):
        files[f"{root_dir}/src/subscriptions.ts"] = (
            "export function subscriptionProvider() {\n"
            "  return {\n"
            '    provider: "revenuecat",\n'
            '    nextStep: "map products, entitlements, and restore purchase behavior before release",\n'
            "  };\n"
            "}\n"
        )
    if has_service(recommendation, "Firebase"):
        files[f"{root_dir}/src/firebase.ts"] = (
            "export function firebaseSurface() {\n"
            "  return {\n"
            "    auth: true,\n"
            "    push: true,\n"
            '    nextStep: "replace placeholder config with project-specific credentials",\n'
            "  };\n"
            "}\n"
        )
    return files


def build_data_pipeline_plan(project_name: str, recommendation: ProjectRecommendation) -> StarterScaffoldPlan:
    package_name = slugify_project_name(project_name)
    root_dir = "starter/data_pipeline"
    return StarterScaffoldPlan(
        label="Data pipeline",
        root_dir=root_dir,
        run_hint=f"uv run --project starter/data_pipeline python -m {package_name}.main sample_input.csv",
        files={
            f"{root_dir}/pyproject.toml": (
                "[build-system]\n"
                'requires = ["setuptools>=75"]\n'
                'build-backend = "setuptools.build_meta"\n\n'
                "[project]\n"
                f'name = "{package_name}-pipeline"\n'
                'version = "0.1.0"\n'
                f'description = "Polars and DuckDB starter pipeline for {project_name}"\n'
                'requires-python = ">=3.12"\n'
                f"dependencies = {toml_string_list(['duckdb>=1.0.0', 'polars>=1.8.0', 'pydantic>=2.0'])}\n\n"
                "[project.optional-dependencies]\n"
                f"dev = {toml_string_list(['pytest>=8.0'])}\n\n"
                "[tool.setuptools.package-dir]\n"
                '"" = "src"\n\n'
                "[tool.setuptools.packages.find]\n"
                'where = ["src"]\n\n'
                "[tool.pytest.ini_options]\n"
                'pythonpath = ["src"]\n'
            ),
            f"{root_dir}/sample_input.csv": "name,value\nalpha,10\nbeta,25\ngamma,30\n",
            f"{root_dir}/src/{package_name}/__init__.py": "",
            f"{root_dir}/src/{package_name}/pipeline.py": (
                "from __future__ import annotations\n\n"
                "import duckdb\n"
                "import polars as pl\n"
                "from pathlib import Path\n\n\n"
                "def summarize(path: Path) -> dict[str, int]:\n"
                "    frame = pl.read_csv(path)\n"
                '    if set(frame.columns) != {"name", "value"}:\n'
                '        raise ValueError("Expected columns name,value in sample input")\n'
                "    connection = duckdb.connect()\n"
                "    record = connection.execute(\n"
                '        "select count(*) as rows, sum(value) as total from read_csv_auto(?)",\n'
                "        [str(path)],\n"
                "    ).fetchone()\n"
                '    return {"rows": int(record[0]), "total": int(record[1])}\n'
            ),
            f"{root_dir}/src/{package_name}/main.py": (
                "from __future__ import annotations\n\n"
                "import sys\n"
                "from pathlib import Path\n\n"
                f"from {package_name}.pipeline import summarize\n\n\n"
                "def main(argv: list[str] | None = None) -> int:\n"
                "    args = argv or sys.argv[1:]\n"
                '    source = Path(args[0]) if args else Path("sample_input.csv")\n'
                "    print(summarize(source))\n"
                "    return 0\n\n\n"
                'if __name__ == "__main__":\n'
                "    raise SystemExit(main())\n"
            ),
            f"{root_dir}/tests/test_pipeline.py": (
                "from __future__ import annotations\n\n"
                "from pathlib import Path\n\n"
                f"from {package_name}.pipeline import summarize\n\n\n"
                "def test_summarize_sample_input() -> None:\n"
                '    result = summarize(Path("sample_input.csv"))\n'
                '    assert result == {"rows": 3, "total": 65}\n'
            ),
            f"{root_dir}/README.md": (
                f"# {project_name} Data Pipeline Starter\n\n"
                "This scaffold mirrors the recommended analytical stack with Polars for "
                "transforms, DuckDB for local queryability, and pytest coverage for the first "
                "data contract checks.\n"
            ),
        },
    )


def build_general_plan(project_name: str, recommendation: ProjectRecommendation) -> StarterScaffoldPlan:
    package_name = slugify_project_name(project_name)
    root_dir = "starter/app"
    return StarterScaffoldPlan(
        label="General app",
        root_dir=root_dir,
        run_hint="python main.py",
        files={
            f"{root_dir}/pyproject.toml": (
                "[project]\n"
                f'name = "{package_name}-app"\n'
                'version = "0.1.0"\n'
                f'description = "Starter app scaffold for {project_name}"\n'
                'requires-python = ">=3.12"\n'
                f"dependencies = {toml_string_list(['pydantic>=2.0'])}\n"
            ),
            f"{root_dir}/main.py": (
                "from __future__ import annotations\n\n"
                "from pydantic import BaseModel\n\n\n"
                "class AppStatus(BaseModel):\n"
                "    ready: bool\n"
                "    message: str\n\n\n"
                "def main() -> int:\n"
                f'    payload = AppStatus(ready=True, message="{project_name} starter app ready")\n'
                "    print(payload.model_dump_json())\n"
                "    return 0\n\n\n"
                'if __name__ == "__main__":\n'
                "    raise SystemExit(main())\n"
            ),
            f"{root_dir}/README.md": (
                f"# {project_name} App Starter\n\n"
                "This is the balanced fallback scaffold when a more specific stack profile has not been selected yet.\n"
            ),
        },
    )


def build_admin_dashboard_plan(project_name: str) -> dict[str, str]:
    """Generate a minimal Vite + React admin dashboard scaffold."""
    root_dir = "starter/admin_dashboard"
    slug = slugify_project_name(project_name)
    return {
        f"{root_dir}/package.json": (
            "{\n"
            f'  "name": "{slug}-admin",\n'
            '  "private": true,\n'
            '  "type": "module",\n'
            '  "scripts": {\n'
            '    "dev": "vite",\n'
            '    "build": "vite build",\n'
            '    "test": "npx playwright test"\n'
            "  },\n"
            '  "dependencies": {\n'
            '    "react": "^19",\n'
            '    "react-dom": "^19",\n'
            '    "react-router-dom": "^7"\n'
            "  },\n"
            '  "devDependencies": {\n'
            '    "@vitejs/plugin-react": "^4",\n'
            '    "vite": "^6",\n'
            '    "typescript": "^6",\n'
            '    "@playwright/test": "^1"\n'
            "  }\n"
            "}\n"
        ),
        f"{root_dir}/vite.config.ts": (
            "import react from '@vitejs/plugin-react';\n"
            "import { defineConfig } from 'vite';\n\n"
            "export default defineConfig({ plugins: [react()] });\n"
        ),
        f"{root_dir}/src/main.tsx": (
            "import { StrictMode } from 'react';\n"
            "import { createRoot } from 'react-dom/client';\n"
            "import { BrowserRouter, Route, Routes } from 'react-router-dom';\n"
            "import { DashboardLayout } from './DashboardLayout';\n\n"
            "createRoot(document.getElementById('root')!).render(\n"
            "  <StrictMode>\n"
            "    <BrowserRouter>\n"
            "      <Routes>\n"
            "        <Route path='/' element={<DashboardLayout />} />\n"
            "      </Routes>\n"
            "    </BrowserRouter>\n"
            "  </StrictMode>,\n"
            ");\n"
        ),
        f"{root_dir}/src/DashboardLayout.tsx": (
            "export function DashboardLayout() {\n"
            "  return (\n"
            "    <main style={{ padding: '2rem', fontFamily: 'system-ui' }}>\n"
            f"      <h1>{project_name} Admin</h1>\n"
            "      <p>Auth-protected dashboard shell. Connect to the backend API client.</p>\n"
            "    </main>\n"
            "  );\n"
            "}\n"
        ),
        f"{root_dir}/src/api.ts": (
            f"const BASE_URL = import.meta.env.VITE_API_URL ?? 'http://localhost:8000';\n\n"
            "export async function fetchStatus(): Promise<Record<string, unknown>> {\n"
            "  const res = await fetch(`${BASE_URL}/status`);\n"
            "  return res.json() as Promise<Record<string, unknown>>;\n"
            "}\n"
        ),
        f"{root_dir}/tests/dashboard.spec.ts": (
            "import { expect, test } from '@playwright/test';\n\n"
            "test('dashboard loads', async ({ page }) => {\n"
            "  await page.goto('/');\n"
            f"  await expect(page.getByText('{project_name} Admin')).toBeVisible();\n"
            "}};\n"
        ),
        f"{root_dir}/README.md": (
            f"# {project_name} Admin Dashboard\n\n"
            "Minimal Vite + React SPA scaffold for the companion admin UI.\n"
            "Run `npm install && npm run dev` to start the dev server.\n"
        ),
    }


def build_starter_scaffold_plan(project_name: str, recommendation: ProjectRecommendation) -> StarterScaffoldPlan:
    product_shape = recommendation.product_shape
    if product_shape == "cli tool":
        plan = build_cli_tool_plan(project_name, recommendation)
    elif product_shape == "api service":
        plan = build_api_service_plan(project_name, recommendation)
    elif product_shape == "web app":
        plan = build_web_app_plan(project_name, recommendation)
    elif product_shape == "mobile app":
        plan = build_mobile_app_plan(project_name, recommendation)
    elif product_shape == "data pipeline":
        plan = build_data_pipeline_plan(project_name, recommendation)
    else:
        plan = build_general_plan(project_name, recommendation)

    files = dict(plan.files)
    cli_property_test = build_cli_hypothesis_test(project_name, recommendation)
    if cli_property_test is not None:
        path, content = cli_property_test
        files[path] = content
    files.update(build_api_optional_files(project_name, recommendation))
    if plan.root_dir == "starter/web_app":
        files.update(build_web_optional_files(recommendation))
    if plan.root_dir == "starter/mobile_app":
        files.update(build_mobile_optional_files(recommendation))
    if any("dashboard" in s for s in recommendation.suggested_companion_surfaces):
        files.update(build_admin_dashboard_plan(project_name))
    env_example = service_env_example(project_name, recommendation, plan.root_dir)
    if env_example is not None:
        path, content = env_example
        files[path] = content
    api_example = api_env_example(project_name, recommendation, plan.root_dir)
    if api_example is not None:
        path, content = api_example
        existing = files.get(path, "")
        if existing:
            files[path] = existing.rstrip() + "\n\n" + content
        else:
            files[path] = content
    files[f"{plan.root_dir}/README.md"] = files.get(f"{plan.root_dir}/README.md", "")
    files["starter/README.md"] = starter_readme(project_name, recommendation, plan)
    return StarterScaffoldPlan(label=plan.label, root_dir=plan.root_dir, run_hint=plan.run_hint, files=files)


def write_starter_scaffold(destination_root: Path, plan: StarterScaffoldPlan) -> list[Path]:
    created: list[Path] = []
    for relative_path, content in sorted(plan.files.items()):
        path = destination_root / relative_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        created.append(path)
    return created
